interface Car {
    brand: string;
    model: string;
    version: string;
    year: string;
    colour: string;
    category: string;
    carFeatures: string[];
    location: string;
    vehicleType: string;
    status: string;
    services: string[];
    gccSpecs: boolean;
    sIprice: string;
    fIprice: string;
    transmission: string;
    cruiseControl: boolean;
    FuelType: string;
    engineCapacity: string;
    luggageBootCapacity: string;
    engineSize: string;
    bluetooth: boolean;
    aux: boolean;
    seater: string;
    navigation: boolean;
    parkSense: boolean;
    appleCarPlay: boolean;
    isoFix: boolean;
    sunRoof: boolean;
    pushButton: boolean;
    lcd: boolean;
    rearCamera: boolean;
    colourInterior: string;
    colourExterior: string;
    description: string;
    dprice: string;
    dnumOFFreeKMs: string;
    ddeliveryCharges: string;
    dminimumDays: string;
    dpriceAfterFreeKMs: string;
    dfreeCancellation: boolean;
    dcancellationCharge: string;
    wprice: string;
    wnumOFFreeKMs: string;
    wdeliveryCharges: string;
    wpriceAfterFreeKMs: string;
    wfreeCancellation: boolean;
    wcancellationCharge: string;
    m1price: string;
    m1numOFFreeKMs: string;
    m1deliveryCharges: string;
    m1priceAfterFreeKMs: string;
    m1freeCancellation: boolean;
    m1cancellationCharge: string;
    m3price: string;
    m3numOFFreeKMs: string;
    m3deliveryCharges: string;
    m3priceAfterFreeKMs: string;
    m3freeCancellation: boolean;
    m3cancellationCharge: string;
    m6price: string;
    m6numOFFreeKMs: string;
    m6deliveryCharges: string;
    m6priceAfterFreeKMs: string;
    m6freeCancellation: boolean;
    m6cancellationCharge: string;
    m9price: string;
    m9numOFFreeKMs: string;
    m9deliveryCharges: string;
    m9priceAfterFreeKMs: string;
    m9freeCancellation: boolean;
    m9cancellationCharge: string;
    extraMileageCost: string;
    cdwInsurancePerDay: string;
    securityDeposit: string;
    excessClaimAmount: string;
    deliveryAndPickUpCharges: string;
    specialNoteForCustomers: string;
    paymentMethods: string[];
    carImages: string[];
    parkingSense: boolean;
  }
  
  const defaultCarValues: Car = {
    brand: '',
    model: '',
    version: '',
    year: '',
    colour: '',
    category: '',
    carFeatures: [],
    location: '',
    vehicleType: '',
    status: '',
    services: [],
    gccSpecs: false,
    sIprice: '',
    fIprice: '',
    transmission: '',
    cruiseControl: false,
    FuelType: '',
    engineCapacity: '',
    luggageBootCapacity: '',
    engineSize: '',
    bluetooth: false,
    aux: false,
    seater: '',
    navigation: false,
    parkSense: false,
    appleCarPlay: false,
    isoFix: false,
    sunRoof: false,
    pushButton: false,
    lcd: false,
    rearCamera: false,
    colourInterior: '',
    colourExterior: '',
    description: '',
    dprice: '',
    dnumOFFreeKMs: '',
    ddeliveryCharges: '',
    dminimumDays: '',
    dpriceAfterFreeKMs: '',
    dfreeCancellation: false,
    dcancellationCharge: '',
    wprice: '',
    wnumOFFreeKMs: '',
    wdeliveryCharges: '',
    wpriceAfterFreeKMs: '',
    wfreeCancellation: false,
    wcancellationCharge: '',
    m1price: '',
    m1numOFFreeKMs: '',
    m1deliveryCharges: '',
    m1priceAfterFreeKMs: '',
    m1freeCancellation: false,
    m1cancellationCharge: '',
    m3price: '',
    m3numOFFreeKMs: '',
    m3deliveryCharges: '',
    m3priceAfterFreeKMs: '',
    m3freeCancellation: false,
    m3cancellationCharge: '',
    m6price: '',
    m6numOFFreeKMs: '',
    m6deliveryCharges: '',
    m6priceAfterFreeKMs: '',
    m6freeCancellation: false,
    m6cancellationCharge: '',
    m9price: '',
    m9numOFFreeKMs: '',
    m9deliveryCharges: '',
    m9priceAfterFreeKMs: '',
    m9freeCancellation: false,
    m9cancellationCharge: '',
    extraMileageCost: '',
    cdwInsurancePerDay: '',
    securityDeposit: '',
    excessClaimAmount: '',
    deliveryAndPickUpCharges: '',
    specialNoteForCustomers: '',
    paymentMethods: [],
    carImages: [],
    parkingSense: false,
  };
  
  export type { Car };
  export { defaultCarValues };
  